apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-example-com
  namespace: monitoring
spec:
  secretName: grafana-example-com
  issuerRef:
    name: kubeflow-self-signing-issuer
    kind: ClusterIssuer
  commonName: grafana.example.com
  dnsNames:
    - grafana.example.com
