apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kiali-example-com
  namespace: istio-system
spec:
  secretName: kiali-example-com
  issuerRef:
    name: kubeflow-self-signing-issuer
    kind: ClusterIssuer
  commonName: kiali.example.com
  dnsNames:
    - kiali.example.com
