apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
spec:
  project: kubeflow
  source:
    repoURL: https://github.com/ybudnyi/argoflow.git
    targetRevision: HEAD
    path: .
    kustomize:
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
