apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admission-webhook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ybudnyi/manifests.git
    targetRevision: HEAD
    path: apps/admission-webhook/upstream/overlays/cert-manager
    kustomize:

  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
