apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ybudnyi/manifests.git
    targetRevision: HEAD
    path: common/cert-manager/kubeflow-issuer/base
    kustomize:

  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
