apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter-web-app 
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    targetRevision: HEAD
    path: apps/jupyter/jupyter-web-app/upstream/overlays/istio
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
