apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfserving-model
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    targetRevision: HEAD
    path: contrib/kserve/models-web-app/overlays/kubeflow
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
