apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeflow/manifests.git
    targetRevision: HEAD
    path: common/knative/knative-serving/overlays/gateways
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
