apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notebook-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ybudnyi/kubeflow-1.6.git
    targetRevision: HEAD
    path: apps/jupyter/notebook-controller/upstream/overlays/kubeflow
    kustomize:
      version: v5.0.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
