apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oidc-authservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ybudnyi/kubeflow-1.6.git
    targetRevision: HEAD
    path: common/oidc-authservice/base
    kustomize:
      version: v5.0.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
