apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ybudnyi/manifests.git
    targetRevision: HEAD
    path: apps/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
    kustomize:
      version: v5.0.0
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
