apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tensorboards-controller
  namespace: argocd
spec:
  project: defaulta
  source:
    repoURL: https://github.com/ybudnyi/manifests.git
    targetRevision: HEAD
    path: apps/tensorboard/tensorboard-controller/upstream/overlays/kubeflow
    kustomize:
      version:
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
