apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "S9M+NDCaVgTO7sDQOz6ERTZwyOA3SqQljo5oV2oDGpASaUpZBD+w1ryj9h7Yi5Fw\nqiuSn/TRAuBqwDRUbT9rHxlstvIOQvDfPT4u+/tWwyH5C3pY80F649ZCTq7fHwwF\nXanrhaEACf3xWAaqCmQPjSSxGUWCuB4oGDEIizlVos4="
